### ISSUE TITLE
Implementing trade offers (and handling)

### ISSUE THREAD

**Issue by ryanwse** [ryanwse/steam-tradeoffer-framework#1]
So far, quite a bit of work has been done locally towards implementing trade offers (and handling). This dedicated to putting together a road map in order to complete the implementation of these features. An ideal implementation is one that is elegant and easy to use, and well documented.

- [ ] Complete documentation of TradeOffer, TradeItem and TradeOfferHandler classes.
- [ ] Implement Guava Optionals wherever null values have the potential to appear.
- [ ] Handle unix timestamps with a value of (0) properly.
- [ ]  Finalize variable & method naming for TradeOffer and TradeOfferHandler classes.
